### ISSUE TITLE
Cannot import whither.base.objects.Window

### ISSUE THREAD

**Issue by TLATER** [Antergos/whither#3]
I'm trying to run the [lightdm web-greeter](https://github.com/Antergos/web-greeter) on Gentoo, but find that it fails when trying to import `whither.base.objects.Window`.

Trying to run `from whither.base.objects import Window` manually in a python shell results in the same issue:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/whither/base/objects.py", line 75, in <module>
    class BaseObject(metaclass=MCS):
  File "/usr/lib64/python3.5/site-packages/whither/base/metaclasses.py", line 52, in __new__
    super(self, self).__init_subclass__(**kwargs)
AttributeError: 'super' object has no attribute '__init_subclass__'
```

Looking at `metaclasses.py` I should probably mention that this is running under python3.5.4.

Is this object not supposed to be imported and should I leave an issue with the web-greeter project? Did I make a mistake compiling something along the way? I'm happy to supply my ebuild files for this if those would be helpful.

**Comment by TwilyName** [comment]
I'm on Gentoo too, and with Python 3.6 as default everything works well
